### ISSUE TITLE
DDE vignette - Error happens in Julia. MethodError: no method matching promote_tspan

### ISSUE THREAD

**Issue by darthaline** [SciML/diffeqr#29]
Hello! I'm getting an error when trying to run the [DDE vignette](https://cran.csiro.au/web/packages/diffeqr/vignettes/dde.html).

[Detailed description with session info](https://darthaline.github.io/diffeqrVignette/delayVignette.nb.html).

**Comment by ChrisRackauckas** [comment]
Is this with Julia v1.5?

**Comment by darthaline** [comment]
yes

**Comment by ChrisRackauckas** [comment]
What version of DiffEqBase do you have? `]st -m` in Julia. It looks like you have a very old version. Did you `]up`?

**Comment by darthaline** [comment]
I've had DiffEqBase v6.10.0, updated to DiffEqBase v6.49.0. Seems like it resolved it, thank you very much!

I also wanted to ask, if it is possible to run this calculation with isoutofdomain option, and if so, how would I do it?

**Comment by ChrisRackauckas** [comment]
You need to pass a function to `isoutofdomain`. I haven't tested it, but just passing a simple R function that matches the signature in https://diffeq.sciml.ai/stable/basics/common_solver_opts/#Miscellaneous should be fine. I'll close this, and yeah... when Julia v1.6 is released the default version should be diffeqr safe, so in about a month this trap is probably fixed for good. Thanks for the report!
