### ISSUE TITLE
MethodError: no method matching EnsembleGPUArray()

### ISSUE THREAD

**Issue by Jack-H-Laverick** [SciML/diffeqr#42]
Hi,

I've been running some of your example code, and am really excited by the performance boost a Julia back-end could mean for my work! 

Everything runs great for me, except the GPU example. 

de$solve(ensembleprob, de$Tsit5(), degpu$EnsembleGPUArray(), trajectories = trajectories, saveat = saveat)

returns for me:

Error: Error happens in Julia.
MethodError: no method matching EnsembleGPUArray()

I've tried uninstalling and reinstalling the development version of diffeqr but this hasn't solved things. I'm a seasoned R user but know nothing about Julia!

**Comment by Jack-H-Laverick** [comment]
After some digging it looks like the example might be missing a backend argument for EnsembleGPUArray().

Looking at Julia docs this could be of the form EnsembleGPUArrayl(CUDA.CUDABackend()), but I haven't got this to work with diffeqr syntax yet.

Attempts such as :

de$solve(ensembleprob, de$Tsit5(), degpu$EnsembleGPUArray(degpu$CUDABackend()), trajectories = trajectories, saveat = saveat)

are met with:

Error in JuliaCall::julia_do.call(func_name = fname, list(...), need_return = match.arg(need_return),  : 
  attempt to apply non-function

So I'm failing to specify the backend correctly. This is monkey meets typewriter stuff for the moment.

**Comment by ChrisRackauckas** [comment]
I'm getting a solution together in https://github.com/SciML/diffeqr/pull/43

**Comment by Jack-H-Laverick** [comment]
Thank you!

**Comment by ChrisRackauckas** [comment]
This is fixed in the v2 release. See the new docs. Also, much faster.

**Comment by Jack-H-Laverick** [comment]
That's great, thanks for getting that together so fast. 

I'm seeing a ~300x speed up using the GPU over calling C-code through deSolve in serial! Interestingly for me there's minimal difference using diffeqr for the GPU example vs running it in pure Julia.

One thing though, shouldn't the EnesmbleGPUArray example in the docs also use degpu$GPUTsit5() ?

**Comment by ChrisRackauckas** [comment]
yes it should. If there's a spot where that's missing, can you PR to fix the typo?
